### ISSUE TITLE
Single-End reads?

### ISSUE THREAD

**Issue by marencc** [ChangLab/FAST-iCLIP#29]
Dear Developer, 

My congratulations for this excellent pipeline. I would like to know if your pipeline is enabled for single-end reads. In the lab I am working, they preferred single-end for budget purposes. It is not enabled, what changes would you suggest that I do, so that I can analyze my data? (Or else, Is there a problem if I just have single-end reads?)

Also, is it necessary to have, at least two replicates?  

Many thanks for your help and support! 

Maria

**Comment by bdo311** [comment]
1) The pipeline is single-end by default so you should have no problem.

2) Generally it's nice to have at least 2 replicates in order to maximize robustness, but if you only have 1 you can split your fastq file into 2 equal pieces.
